// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const web = FirebaseOptions(
    apiKey: 'AIzaSyAaVNwwjIGz7BrrYRCJOsfRughao9LCgG8',
    appId: '1:660238440329:web:c07f8f3299bd0de7b93358',
    messagingSenderId: '660238440329',
    projectId: 'go-router-sample-220927',
    authDomain: 'go-router-sample-220927.firebaseapp.com',
    storageBucket: 'go-router-sample-220927.appspot.com',
  );

  static const android = FirebaseOptions(
    apiKey: 'AIzaSyBfwK5iBq7767R6y7fA8r6hh90VYFg380o',
    appId: '1:660238440329:android:5e68d9c8d47cf52fb93358',
    messagingSenderId: '660238440329',
    projectId: 'go-router-sample-220927',
    storageBucket: 'go-router-sample-220927.appspot.com',
  );

  static const ios = FirebaseOptions(
    apiKey: 'AIzaSyDCzsdY6JuPKIQK3B2J2yKjN68CAiipOQM',
    appId: '1:660238440329:ios:2843f881d8e31a6db93358',
    messagingSenderId: '660238440329',
    projectId: 'go-router-sample-220927',
    storageBucket: 'go-router-sample-220927.appspot.com',
    iosClientId:
        '660238440329-fvpq66a5e4ki29n43fg4e5hk04vtkjt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.goRouterSampleFn',
  );

  static const macos = FirebaseOptions(
    apiKey: 'AIzaSyDCzsdY6JuPKIQK3B2J2yKjN68CAiipOQM',
    appId: '1:660238440329:ios:2843f881d8e31a6db93358',
    messagingSenderId: '660238440329',
    projectId: 'go-router-sample-220927',
    storageBucket: 'go-router-sample-220927.appspot.com',
    iosClientId:
        '660238440329-fvpq66a5e4ki29n43fg4e5hk04vtkjt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.goRouterSampleFn',
  );
}
